name: CI
on:
  push:
    branches: [ master ]
    tags:
      - '*'
  pull_request:
    branches: [ master ]
jobs:
  build:
    name: Build JNI lib for ${{ matrix.build }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - build: x86_64-linux
            os: ubuntu-latest
            docker: true
          - build: aarch64-linux
            os: ubuntu-latest
            target: aarch64-unknown-linux-gnu
            docker: true
          - build: x86_64-macos
            os: macos-latest
            target: x86_64-apple-darwin
          - build: aarch64-macos
            os: macos-latest
            target: aarch64-apple-darwin
          - build: x86_64-windows
            os: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v4
      with:
        java-version: '8'
        distribution: 'temurin' # 或者 'zulu'
        architecture: x64
    - name: Set up Rust
      uses: dtolnay/rust-toolchain@master
      with:
        toolchain: 1.94.1
        components: rustfmt
    # Binary compatibility settings from bytecodealliance/wasmtime
    - name: Binary compatibility settings (macOS)
      if: ${{ startsWith(matrix.os, 'macos') }}
      run: echo 'MACOSX_DEPLOYMENT_TARGET=10.9' >> $GITHUB_ENV
    - name: Binary compatibility settings (Windows)
      if: ${{ startsWith(matrix.os, 'windows') }}
      run: echo 'RUSTFLAGS=-Ctarget-feature=+crt-static' >> $GITHUB_ENV
    - name: Set build target for cross-compiling
      if: matrix.target != ''
      run: |
        echo CARGO_BUILD_TARGET=${{ matrix.target }} >> build_env.txt
        echo JNILIB_RUST_TARGET=${{ matrix.target }} >> build_env.txt
        echo GRADLE_ARGS="${GRADLE_ARGS} -x test">> build_env.txt
        cat build_env.txt >> $GITHUB_ENV
        rustup target add ${{ matrix.target }}
    # Run gradle in a docker container to build the JNI lib on Linux for old glibc compatibility
    - name: Build with Gradle (Linux)
      if: ${{ matrix.docker }}
      run: |
        if [ ! -e build_env.txt ]; then
          touch build_env.txt
        fi
        docker build -t build-image ./ci/docker/${{ matrix.build }}
        docker run --rm --volume $PWD:/build --workdir /build \
          --env-file build_env.txt \
          build-image \
          ./gradlew build copyJniLib -x javadoc ${GRADLE_ARGS}
    # Otherwise, run gradle normally to build the JNI lib
    - name: Build with Gradle
      if: ${{ !matrix.docker }}
      run: ./gradlew build copyJniLib ${GRADLE_ARGS}
    - name: List shared library files
      run:
        file build/jni-libs/*
    - name: Save JNI lib output
      if: startsWith(github.ref, 'refs/tags/')
      uses: actions/upload-artifact@v4
      with:
        name: jni-libs-${{ matrix.build }}
        path: build/jni-libs/*
  publish:
    if: startsWith(github.ref, 'refs/tags/')
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 8
      uses: actions/setup-java@v4
      with:
        java-version: '8'
        distribution: 'zulu'
    - name: Restore JNI libs
      uses: actions/download-artifact@v4
      with:
        pattern: jni-libs-*
        path: build/jni-libs
        merge-multiple: true
    - name: Build universal jar
      run: ./gradlew universalJar -x buildJniLib -x copyJniLib
    - id: get-tag-version
      run: |
        version=$(echo ${{ github.ref }} | cut -f3 -d/ | sed 's/^v//')
        echo "version=$version" >> $GITHUB_OUTPUT
    - name: Create release and upload asset
      uses: softprops/action-gh-release@v3
      with:
        files: build/libs/wasmtime-java-*-universal.jar
        token: ${{ secrets.GITHUB_TOKEN }}
